name: Pull Request

on:
  pull_request:
    paths:
      - ".github/workflows/pr.yaml"
      - ".github/workflows/merge.yaml"
      - "srs-ta-example-app/**"
    # All pr's should be made to the dev branch in this design
    branches:
      - 'dev'

jobs:
  pr:
    name: Pull Request
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12

      # TODO: Implement Backend Linters

      # Prettier must be in `package.json`
      - name: Install Node.js dependencies
        run: |
          cd srs-ta-example-app
          npm ci

      - name: Run linters
        uses: wearerequired/lint-action@v1
        with:
          prettier: true
          prettier_dir: srs-ta-example-app/

      # TODO: Implement Backend Tests

      - name: Test Frontend
        run: |
          cd srs-ta-example-app
          npm install
          npm run test

      # TODO: Implement Backend Build Test

      - name: Build Frontend
        run: |
          cd srs-ta-example-app
          npm install
          npm run build

      # TODO: Implement Backend Image Build and Deploy

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: maxwardle/srs-ta-example-app:pr-${{ github.event.number }}

      # TODO: Implement Frontend Openshift Deployment

      # TODO: Implement Backend Openshift Deployment

      # TODO: Implment Test Data Generation

      # TODO: Implement Migration Runner (Mongo DB and DB Migrate)

      # TODO: Implement Functional Tests
