name: Pull Request

on:
  pull_request:
    paths:
      - ".github/workflows/pr.yaml"
      - ".github/workflows/merge.yaml"
      - "srs-ta-example-app/**"
    # All pr's should be made to the dev branch in this design with the exception of hotfixes
    branches:
      - 'dev'


jobs:
  pr:
    name: pull request
    runs-on: ubuntu-latest

    steps:
      - name: Check out
        uses: actions/checkout@v2

      - name: Run linters
        uses: wearerequired/lint-action@v1
        with:
          prettier: true

      # this would run the backend tests if they existed
      - name: Test Backend
        run: |
          cd server

      - name: Test Frontend
        run: |
          cd srs-ta-example-app
          npm install
          npm run test

      # this would test a build of the api if it existed
      - name: Build Backend
        run: |
          cd server

      - name: Build Frontend
        run: |
          cd srs-ta-example-app
          npm install
          npm run build


      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: maxwardle/srs-ta-example-app:pr-${{ github.event.number }}

      # Here would be the final step of deploying this the "PR" docker image to a openshift container for manual inspection